blog6/blog6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

blog6/main/urls.py
from django.urls import path
from .views import *
from . import views


# import domyślnych widoków na potrzeby logowania
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", startpage_response, name="start"),
    path("main_page", views.PostList.as_view(), name="home"),
    path("post/new/", views.post_new, name='post_new'),
    path("signup", signup_view, name='signup'),
    path("<slug:slug>/", views.post_detail, name='post_detail'),
    path("postdel/<slug:slug>/", views.post_delete, name='post_delete'),
    path("postedit/<slug:slug>/", views.post_edit, name='post_edit'),
    path("about", aboutus_view, name='about'),
    path("contact", contact_view, name='contact'),

# ścieżki do widoków logowania/wylogowania
    path("login", auth_views.LoginView.as_view(), name="login"),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("logout-done", logout_done)
]

blog6/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Create your models here.

class Post(models.Model):
    title = models.CharField('Tytuł', max_length=100, unique=True)
    slug = models.SlugField('Odnośnik', default=slugify(title), unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name='Autor')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField('Treść')
    created_on = models.DateTimeField('Stworzony', auto_now_add=True)

    class Meta:
        ordering = ['-created_on']
        verbose_name = 'Wiadomość'
        verbose_name_plural = 'Wiadomości'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', verbose_name='Komentarz')
    author = models.CharField(max_length=30, verbose_name='Autor')
    email = models.EmailField()
    content = models.TextField(verbose_name='Treść')
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']
        verbose_name = 'Komentarz'
        verbose_name_plural = 'Komentarze'

    def __str__(self):
        return 'Comment {} by {}'.format(self.content, self.author)

blog6/main/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ("title", "content")


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Opptional.')
    email = forms.EmailField(max_length=254, help_text='Required. Type a vaild email adress.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'email', 'content')

blog6/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import HttpResponse, Http404
from .models import *
from django.views import generic
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied




# Create your views here.

def startpage_response(request):
    return render(request, "start.html")

def logout_done(request):
    return render(request, "logout-done.html")

def aboutus_view(request):
    return render(request, "about-us.html")

def contact_view(request):
    return render (request, "contact.html")

def signup_view(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

@login_required()
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('home')
    else:
        form = PostForm()
    return render(request, 'post-new.html', {'form': form, })

@login_required()
def post_detail(request, slug):
    template_name = 'post-detail.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    #Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            # return redirect('post_detail')
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                       'comments': comments,
                                       'new_comment': new_comment,
                                       'comment_form': comment_form})

def restrict_user_access(function):
    def wrap(request, *args, **kwargs):
        post = Post.objects.get(slug=kwargs['slug'])
        if post.author != request.user:
            raise PermissionDenied
        return function(request, *args, **kwargs)

    wrap.__doc__ = function.__doc__
    wrap.__name__= function.__name__
    return wrap

@restrict_user_access
@login_required()
def post_delete(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST)
    if request.method == "POST":
        post.author = request.user
        post.delete()
        return redirect('home')
    return render(request, "post-delete.html", {"form": form, "slug": slug})

@restrict_user_access
@login_required()
def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, "post-edit.html", {"form": form, "slug": slug})

class PostList(generic.ListView):
    queryset = Post.objects.filter().order_by("-created_on")
    template_name = "main-page.html"
    paginate_by = 4

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PostList, self).dispatch(*args, **kwargs)

blog6/main/templates/about-us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
 <head>
        <title>Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 16px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid navbar-nav ml-auto">
                <div class="nav-link text-black font-weight-bold">O nas</div>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Wyloguj się</a>
                        </li>

                         <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'contact' %}">Kontakt</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    <div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1 style="font-size: 16px; text-align: center">Ten blog zrobiony został na potrzeby kursu SDA</h1>
        <a href="{% url 'home'%}" class="btn btn-primary btn-sm">Wróć&rarr;</a>
    </form>
      </div>
    </div>
  </div>
</div>

</body>
</html>

blog6/main/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 16px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid navbar-nav ml-auto">
                <a class="btn btn-primary  btn-lg" href="{% url 'post_new' %}">Dodaj nowy post</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                        data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Wyloguj się</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'about' %}">O nas</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'contact' %}">Kontakt</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; Rafał and Mateusz</p>
        </footer>
    </body>
</html>

blog6/main/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
 <head>
        <title>Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 16px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid navbar-nav ml-auto">
                <div class="nav-link text-black font-weight-bold">Kontakt</div>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Wyloguj się</a>
                        </li>

                         <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'about' %}">O nas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    <div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1 style="font-size: 18px">Rafał</h1>
          <p style="font-size: 15px">email: osa535@wp.pl</p>
          <p>tel:</p>
        <h1 style="font-size: 18px">Mateusz</h1>
          <p style="font-size: 15px">email: mateusz.czerniawski@gmail.com</p>
          <p>tel:</p>
        <a href="{% url 'home'%}" class="btn btn-primary btn-sm">Wróć&rarr;</a>
    </form>
      </div>
    </div>
  </div>
</div>
</body>
</html>

blog6/main/templates/logout-done.html
<!DOCTYPE html>
<html>

    <head>
        <title>Logout</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 16px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }


    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid navbar-nav ml-auto">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                        data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">O nas</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Kontakt</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="col-md-20 mt-3 center  top">
            <body style="text-align: center; padding-bottom: 30px">
                <h1 style="font-size: 18px ">Zostałeś wylogowany!</h1>
                <a href="{% url 'login' %}" class="btn btn-primary btn-sm" >Zaloguj się ponownie</a>
            </body>
</html>

blog6/main/templates/main-page.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 16px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Witaj na naszym blogu </h3>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Czytaj więcej &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
<div>
    {% if is_paginated %}
  <nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; POPRZEDNIA STRONA </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NASTĘPNA STRONA &raquo;</a></li>

    {% endif %}
  </ul>
  </nav>
</div>
{% endif %}
{%endblock%}

blog6/main/templates/post-delete.html
<!DOCTYPE html>
<html>

    <head>
        <title>Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 16px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }

    </style>

        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid navbar-nav ml-auto">
                <div class="nav-link text-black font-weight-bold">Usuń post</div>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Wyloguj się</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">O nas</a>
                        </li>
                         <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Kontakt</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
    <form method="POST" class="post-form">
        <h1 style="font-size: 16px; text-align: center">Czy napewno chcesz usunąć ten post? {{ post.title }}</h1>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Usuń</button>
        <a href="{% url 'post_detail' slug %}" class="btn btn-primary btn-sm">Wróć&rarr;</a>
    </form>
      </div>
    </div>
  </div>
</div>

blog6/main/templates/post-detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
        <a href="{% url 'home' %}" class="btn btn-primary btn-sm" style="float: right">Wróć&rarr;</a>
          <a href="{% url 'post_edit' post.slug %}" class="btn btn-primary btn-sm">Edytuj</a>
          <a href="{% url 'post_delete' post.slug %}" class="btn btn-primary btn-sm">Usuń</a>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>Komentarze: {{ comments.count }} </h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.author }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.content | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Twój komentarz oczekuje moderacji
        </div>
        {% else %}
        <h3>Dodaj komentarz</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-sm">Dodaj</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

blog6/main/templates/post-edit.html
<!DOCTYPE html>
<html>

    <head>
        <title>Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 16px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid navbar-nav ml-auto">
                <div class="nav-link text-black font-weight-bold">Edytuj post</div>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Wyloguj się</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">O nas</a>
                        </li>
                         <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Kontakt</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-sm">Edytuj</button>
        <a href="{% url 'post_detail' slug %}" class="btn btn-primary btn-sm">Wróć&rarr;</a>
    </form>
      </div>
    </div>
  </div>
</div>

blog6/main/templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">tu bedzie wyszukiwarka</h5>
    <div class="card-body">
        <p class="card-text">teeeest</p>
    </div>
</div>
</div>

{% endblock sidebar %}

blog6/main/templates/start.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Start</title>
    <style>
            background-color: black;
    </style>
</head>
<body style="text-align: center">
    <h1>Witaj na blogu Mateusza i Rafała</h1>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
       <p>
    <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-primary btn-lg">Zaloguj się</button></a>
    <a href="{% url 'signup' %}"><button type="button" class="btn btn-outline-secondary btn-lg">Zarejestruj się</button></a>
        </p>
 <p>
    <img src="https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/View_park.jpg/1200px-View_park.jpg" width="50%">
 </p>
</body></html>